### ISSUE TITLE
install errors hugginface and github 

### ISSUE THREAD

**Issue by gitihobo** [facebookresearch/seamless_communication#106]
seamless_m4t>python app.py
\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Traceback (most recent call last):
  File \app.py", line 9, in <module>
    from seamless_communication.models.inference.translator import Translator
ModuleNotFoundError: No module named 'seamless_communication.models'

INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.0

**Comment by samheutmaker** [comment]
Getting the same error on a fresh clone. Python 3.9.

**Comment by ealkanat** [comment]
same here for me.

INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.0

**Comment by ealkanat** [comment]
> same here for me. MacOS
> 
> INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while. ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none) ERROR: No matching distribution found for fairseq2n==0.1.0

I have made a video for SeamlessM4T Macbook installation.
Here is the video -> https://youtu.be/1iMBa_LGkTg

**Comment by cndn** [comment]
Thanks @ealkanat , nice video! Closing this for now, feel free to reopen if issue remains.

**Comment by gitihobo** [comment]
was this fixed in a commit or why is it closed

**Comment by llj0824** [comment]
> was this fixed in a commit or why is it closed

+1 in the video by @ealkanat, he clones [mac-fairseq2](https://www.bing.com/search?q=mac-fairseq2&PC=U316&FORM=CHROMN) and installs it manually.
