### ISSUE TITLE
A way to skip a few tokens?

### ISSUE THREAD

**Issue by zachNA2** [facebookresearch/seamless_communication#110]
Is there a way to allow the model to skip a few tokens during any inferencing? I have a sentence like Hello my name is John.

I would like it for the model to completely ignore the word John. Is there a way to trick the model to skip specific words something along the lines of like "Hello my name is <unk> and then just directly replace the <unk> with John after the translation (T2TT)? (This is just a hypothetical sentence for trying to ask my question)

**Comment by cndn** [comment]
Hey @zachNA2 - in your case is "John" in source sentence and you don't want it to be translated? Maybe look up cross attention matrix and replace the generated tokens which attend to "John"?

**Comment by zachNA2** [comment]
Ill check it out! Thank you!
