### ISSUE TITLE
Generate speech without translation

### ISSUE THREAD

**Issue by huey2531** [facebookresearch/seamless_communication#113]
is it possible to use seamless to generate speech without translating to a different language?

**Comment by jmp84** [comment]
@huey2531 you can select the same source language and target languages.
For example in https://seamless.metademolab.com/demo, you can record some input in your native languages and select that language as target, which will be the same as doing speech recognition.
In https://huggingface.co/spaces/facebook/seamless_m4t you can select the T2ST task and select the same source and target languages, which will be the same as speech synthesis (but that one is very experimental and not evaluated on benchmarks).
