### ISSUE TITLE
Question about weight file save path

### ISSUE THREAD

**Issue by namho-96** [facebookresearch/seamless_communication#114]
Hello.
Thanks for sharing your great research!
I have a question about the process of loading a model.
In my Ubuntu environment, when I load a model with the following code, the model is stored in ".cache/torch/hub".
```
import torch
import torchaudio
from seamless_communication.models.inference import Translator


# Initialize a Translator object with a multitask model, vocoder on the GPU.
translator = Translator("seamlessM4T_large", "vocoder_36langs", torch.device("cuda:0"), torch.float16)
```

I would like to replace this path with a different path and load the model from the changed path. I would be grateful if you could tell me how this is possible.

**Comment by zachNA2** [comment]
You have two options for this. Either you change the path in the asset card so instead of pulling from https://whateverLink it will pull from file://Whatever/your/path/is.

Second option is just moving the model weights into the ~/.cache folder. 

Both are mentioned in #50

**Comment by dawit3228** [comment]
> You have two options for this. Either you change the path in the asset card so instead of pulling from https://whateverLink it will pull from file://Whatever/your/path/is.
> 
> Second option is just moving the model weights into the ~/.cache folder.
> 
> Both are mentioned in #50



missing 1 required positional argument: 'vocoder_name_or_card'

here is the code 

```

breakpoint: "Models/seamlessM4T_v2_large.pt"


translator = Translator(
    model_name_or_card=breakpoint,
    device=torch.device("cuda:0"),
    dtype=torch.float16,
)


```
