### ISSUE TITLE
Question on Fine Tunning: TEXT_TO_TEXT Mode

### ISSUE THREAD

**Issue by hardiksraja** [facebookresearch/seamless_communication#115]
From the Readme, I understand currently it supports fine-tuning for only 3 modes as below,

SPEECH_TO_SPEECH, TEXT_TO_SPEECH, SPEECH_TO_TEXT

In future, will there be a possibility to fine-tune TEXT_TO_TEXT Mode?

**Comment by zachNA2** [comment]
#52

**Comment by sravyapopuri388** [comment]
Text_to_text finetuning can be supported with some code changes to the existing finetuning modes for other tasks. We plan to support this in the future but don't have a ETA yet. https://github.com/facebookresearch/fairseq/tree/nllb/ is a good alternative if you are only interested in T2T task

**Comment by hardiksraja** [comment]
@sravyapopuri388 Noted...Thank you :-)

**Comment by evanbrociner** [comment]
Thank you! If anyone happens to work on this, please let me know
