### ISSUE TITLE
libsndfile is not found error

### ISSUE THREAD

**Issue by erikvullings** [facebookresearch/seamless_communication#117]
Although I've tried installing it on wsl2 (Ubuntu 22.04) and Ubuntu 22.04 LTS, when running the example, I get an error that libsndfile is not found (and yes, I've installed it via miniconda as well as via Ubuntu's apt).

Any suggestions on how to fix this?

```bash
m4t_predict "Hello, world" t2tt nld --src_lang eng
Traceback (most recent call last):
  File "/home/driver/.local/bin/m4t_predict", line 5, in <module>
    from m4t_scripts.predict.predict import main
  File "/home/driver/.local/lib/python3.10/site-packages/m4t_scripts/predict/predict.py", line 10, in <module>
    from seamless_communication.models.inference import Translator
  File "/home/driver/.local/lib/python3.10/site-packages/seamless_communication/models/inference/__init__.py", line 6, in <module>
    from seamless_communication.models.inference.translator import Translator as Translator
  File "/home/driver/.local/lib/python3.10/site-packages/seamless_communication/models/inference/translator.py", line 12, in <module>
    from fairseq2.data import Collater
  File "/home/driver/.local/lib/python3.10/site-packages/fairseq2/data/__init__.py", line 7, in <module>
    from fairseq2.data.cstring import CString as CString
  File "/home/driver/.local/lib/python3.10/site-packages/fairseq2/data/cstring.py", line 58, in <module>
    from fairseq2n.bindings.data.string import CString as CString
  File "/home/driver/.local/lib/python3.10/site-packages/fairseq2n/__init__.py", line 90, in <module>
    _load_sndfile()
  File "/home/driver/.local/lib/python3.10/site-packages/fairseq2n/__init__.py", line 80, in _load_sndfile
    raise OSError(
OSError: libsndfile is not found!. Use your system package manager to install it (e.g. `apt install libsndfile1`).
```

**Comment by bezbahen0** [comment]
@erikvullings I had the same problem. Disabling conda enviroment helped me. For a test, you can look in your ~/.bashrc file and comment out the lines with conda shell initalization and try installing seamless_communication again.

I don't know for what reason this happens, maybe conda changes the paths to find the libs

**Comment by erikvullings** [comment]
@bezbahen0 Thanks for the tip! Indeed, this did the trick for me too, in WSL2 as well as in Ubuntu. 

Perhaps someone with write permissions can add this to the documentation, or, even better, make sure that it also works in a conda environment. 

As a side note, I am a bit surprised that I needed the `libsndfile` - it seems to be used for audio processing, and I was performing a T2TT task, so I assumed it would not need that library.

**Comment by sravyapopuri388** [comment]
Closing this issue as its resolved

**Comment by erikvullings** [comment]
Is it really closed? At least you could mention it in the doc files?

**Comment by fengyunzaidushi** [comment]
> @erikvullings I had the same problem. Disabling conda enviroment helped me. For a test, you can look in your ~/.bashrc file and comment out the lines with conda shell initalization and try installing seamless_communication again.
> 
> I don't know for what reason this happens, maybe conda changes the paths to find the libs

did you mean comment out these code:
```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```
