### ISSUE TITLE
generate wrong audio

### ISSUE THREAD

**Issue by 450586509** [facebookresearch/seamless_communication#121]
These input texts output the wrong speech

```python
#text= "hello, how are you"
text = "oh, what's the matter,oh, what's the matter,what's the matter."

translated_text, wav, sr = translator.predict(
    text,
    "t2st",
    tgt_lang='eng',
    src_lang='eng'
)


```

**Comment by wpl427** [comment]
oh~~~~~~~

**Comment by cndn** [comment]
Hey @450586509 I tried in space demo - which should run as the same under the hood - the model does generate the expected output with your input https://huggingface.co/spaces/facebook/seamless_m4t.

**Comment by cndn** [comment]
Closing for now, if there are still problems feel free to refer to how this demo calls into the model.
