### ISSUE TITLE
Where is Translator.load_model_for_inference or fairseq2 wav2vec model saved default path

### ISSUE THREAD

**Issue by yixiangchen1995** [facebookresearch/seamless_communication#124]
After I use unit_extractor = UnitExtractor(model_name, kmean_uri, device=device)  download model (xlsr2_1b_v2),  I could not find where the model(xlsr2_1b_v2) file saved

**Comment by yixiangchen1995** [comment]
save at .cash

**Comment by Gxhappiness** [comment]
佬，方便加个联系方式沟通下吗
