### ISSUE TITLE
Is the translation process use GPU?

### ISSUE THREAD

**Issue by greagain** [facebookresearch/seamless_communication#125]
I find that the translation is rather slow, I have a 16GB ram & 3060 12GB GPU system, I use nvidia-smi to check during the translation, and it didn't seems use GPU. Is that what it should be?

**Comment by huangwei2913** [comment]
you can choose to use GPU device, i have a nvidia 3090,  the GPU memory is intensively used 
(llama) huangwei@huangwei-MS-7D42:~$ nvidia-smi
Mon Sep  4 11:17:28 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 44%   58C    P5    49W / 350W |  20785MiB / 24576MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1052      G   /usr/lib/xorg/Xorg                106MiB |
|    0   N/A  N/A      1346      G   /usr/bin/gnome-shell               35MiB |
|    0   N/A  N/A    243974      G   ...RendererForSitePerProcess       44MiB |
|    0   N/A  N/A    271559      C   python                          20594MiB |
+-----------------------------------------------------------------------------+

**Comment by greagain** [comment]
Thanks for confirm, but how do I choose to use GPU? No mention of this in the readme file.

**Comment by cndn** [comment]
Hey @greagain - There are device and dtype as arguments in Translator initializer, could you try passing in torch.device("cuda:0") and torch.float16 and see if it works? https://github.com/facebookresearch/seamless_communication/blob/main/src/seamless_communication/models/inference/translator.py#L55-L56

**Comment by greagain** [comment]
Thanks, get it.

**Comment by fjesikfjdskl** [comment]
Hello, what is your GPU utilization rate here?My current 4090d graphics card is only 50% utilized!

**Comment by christopherpickering** [comment]
For macbook pro m1, I added `device= torch.device("mps")` on line 91 to make it use gpu.

Or, to fix the cli, you could edit `/cli/m4t/predict/predict.py` around line 200. Add mps as a torch option:

```py
if torch.backends.mps.is_available():
        device = torch.device("mps")
        dtype = torch.float16

    elif torch.cuda.is_available():
        device = torch.device("cuda:0")
        dtype = torch.float16
    else:
        device = torch.device("cpu")
        dtype = torch.float32
```
