### ISSUE TITLE
The problem of downloading Seamless align data

### ISSUE THREAD

**Issue by yangsuxia** [facebookresearch/seamless_communication#129]
Hi ，
Can I download audio-to-text data in languages other than the following? eg from portuguese audio to portuguese text
![image](https://github.com/facebookresearch/seamless_communication/assets/34536059/5b3915f9-e0a6-4f4c-8a95-46f06f63ad0e)

**Comment by Celebio** [comment]
Hi @yangsuxia,  thank you for your interest on SeamlessAlign!
Unfortunately, the listed directions are the only available ones.

Best regards,
Onur
