### ISSUE TITLE
How to ASR a 30 minutes audio file

### ISSUE THREAD

**Issue by echogit** [facebookresearch/seamless_communication#135]
I'm trying to use  SeamlessM4T on a google colab notebook, I have already the audio file, what is the minimal code to make he transcription of the audio of a supported language (brazilian portuguese in my case).
I tried doing the following:
```
!pip install git+https://github.com/facebookresearch/seamless_communication
!pip install pre-commit
!pip install datasets
!pip install torchaudio
!pip install soundfile
!pip install librosa
!pip install fairseq2==0.1.0

import torch
from seamless_communication.models.inference import Translator

print("Cuda available",torch.cuda.is_available())

print("Mem allocated:",torch.cuda.memory_allocated())

# Initialize a Translator object with a multitask model, vocoder on the GPU.
translator = Translator("seamlessM4T_large", vocoder_name_or_card="vocoder_36langs", device=torch.device("cuda:0"), dtype=torch.float16)

# ASR
transcribed_text, _, _ = translator.predict("/content/drive/MyDrive/Audios/Voice 022.wav", "asr", "por")

print(transcribed_text)
# Save the transcribed text to a file
with open('/content/drive/MyDrive/Audios/transcript-seamlessm4t.txt', "w") as f:
    f.write(transcribed_text)
```

I'm getting the result:
```
..
Downloading the checkpoint of the model 'seamlessM4T_large'...
100%|██████████| 10.7G/10.7G [00:57<00:00, 201MB/s]
Downloading the tokenizer of the model 'seamlessM4T_large'...
100%|██████████| 4.93M/4.93M [00:00<00:00, 88.0MB/s]
Downloading the checkpoint of the model 'vocoder_36langs'...
100%|██████████| 160M/160M [00:01<00:00, 149MB/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-1-4cac63b6d547>](https://localhost:8080/#) in <cell line: 21>()
     19 # ASR
     20 # This is equivalent to S2TT with `<tgt_lang>=<src_lang>`.
---> 21 transcribed_text, _, _ = translator.predict("/content/drive/MyDrive/Audios/Voice 022.wav", "asr", "por")
     22 
     23 print(transcribed_text)

22 frames
[/usr/local/lib/python3.10/dist-packages/fairseq2/nn/transformer/relative_attention.py](https://localhost:8080/#) in forward(self, seqs)
    291 
    292         if seq_len > self.max_seq_len:
--> 293             raise ValueError(
    294                 f"The input sequence length must be less than or equal to the maximum sequence length ({self.max_seq_len}), but is {seq_len} instead."
    295             )

ValueError: The input sequence length must be less than or equal to the maximum sequence length (4096), but is 92933 instead.
```

Is there a limit of tokens for this model?

**Comment by debrupf2946** [comment]
yes there is max sequence length, Try to chunk down audio clips and then send in batches

**Comment by echogit** [comment]
Would it work better than the open-source whisper or openai paid whisper? I
already got it done using those solutions. My main problem is to identify
and separate each one of the people talking on the audio, which was
recorded at a meeting.

**Comment by Mortimerp9** [comment]
M4T is made for translation/transcribing short audio segments so you can't really feed it such big segments. As per @debrupf2946, segmenting would be the solution. If you can segment in "semantic" units (sentences for instance) it will translate better in theory.

You could use Whisper OSS to identify segments and then apply M4T on these segments, just as a way for you to see if M4T works better for you.

Another solution is to use a VAD like [Silero](https://github.com/snakers4/silero-vad)

**Comment by echogit** [comment]
> Whisper OSS

Would that work in a meeting setting, for example? I need a took that could preferably distinguish each person who's talking, It would even learn the voice of each one if needs previoulsy. 
I need something that could result in something like:
person1: hi all we are here for....
person2: Our intentions is to...

Then I could change the label for the person's name.
I'd have to be able to get the sentences independently even if there is overlapping between phrases

**Comment by haiderasad** [comment]
> > Whisper OSS
> 
> Would that work in a meeting setting, for example? I need a took that could preferably distinguish each person who's talking, It would even learn the voice of each one if needs previoulsy. I need something that could result in something like: person1: hi all we are here for.... person2: Our intentions is to...
> 
> Then I could change the label for the person's name. I'd have to be able to get the sentences independently even if there is overlapping between phrases

@echogit you need to apply speaker diarization in order to get segments for each separated speaker, you can use https://github.com/m-bain/whisperX and https://github.com/pyannote/pyannote-audio

**Comment by aravind-muraleedharan** [comment]
Hi @echogit,

you may please refer to a sample script that I wrote to translate/ transcribe lengthy audio clips. 

https://github.com/aravind-muraleedharan/tiny-scripts/blob/main/translate_audio.py
