### ISSUE TITLE
Is it possible to use T2ST with a reference audio?

### ISSUE THREAD

**Issue by evanbrociner** [facebookresearch/seamless_communication#142]

**Comment by cndn** [comment]
Hey @evanbrociner Could you elaborate? T2ST generates a speech in target audio, what is a reference audio for?

**Comment by evanbrociner** [comment]
@cndn no problem thank you. What I am looking to do is use T2ST, but have the speech output be cloned to a given speaker. Is this possible?

**Comment by cndn** [comment]
> @cndn no problem thank you. What I am looking to do is use T2ST, but have the speech output be cloned to a given speaker. Is this possible?

In this case you need to train your own vocoder with that specific speaker, following https://github.com/facebookresearch/seamless_communication/issues/111

**Comment by rhnaxifg4y** [comment]
@evanbrociner any luck here?
