### ISSUE TITLE
Setting local path for manually downloaded checkpoints not working!

### ISSUE THREAD

**Issue by arash-aut** [facebookresearch/seamless_communication#143]
Hey everyone,
I noticed from solved issues that we can change the path for checkpoints [in this file](https://github.com/facebookresearch/seamless_communication/blob/main/src/seamless_communication/assets/cards/seamlessM4T_large.yaml#L10) and use manually downloaded checkpoints instead of downloading them while inferring! However, I changed the proposed file as it was mentioned and it tried to download the checkpoint again from the internet anyway!
I also, set a wrong path to that file and it continued downloading... It seems that it has nothing to do with the checkpoint's path!

Here is the way I tried to change the path:
`checkpoint: "file://home/arash/Downloads/Seamless M4T-Large/multitask_unity_large.pt"`

I'd be gratful if anyone could help me solve this problem.
Thank you in advance.
Arash

**Comment by YRH0** [comment]
I meet the same question!

**Comment by YRH0** [comment]
> I meet the same question!

![image](https://github.com/facebookresearch/seamless_communication/assets/74707759/5d92eb5d-214a-43f6-9b4d-711982d0938c)
获取的是解释器的路径，所以修改项目下的文件路径没用

**Comment by YRH0** [comment]
获取的是解释器路径
![image](https://github.com/facebookresearch/seamless_communication/assets/74707759/e25e77d1-8596-4be5-9c4e-7ba7b51a5c41)

**Comment by YRH0** [comment]
> The card is inheriting from unity_nllb-100.yaml that has a path to tokenizer:
> 
> ```
> model_type: unity
> tokenizer: "https://huggingface.co/facebook/seamless-m4t-large/resolve/main/tokenizer.model"
> default_lang: eng
> langs:
> ...
> ```
> 
> Are you sure that it is not the tokenizer that is getting downloaded?
> 
> Also, do you confirm that you've installed seamless_communication in editable mode? (`pip install -e .`).
Using pip install -e . can help resolve the problem. Conversely, using pip install . raise issues during the installation process.

**Comment by arash-aut** [comment]
Thank you @mavlyutovr 
I installed the toolkit in editable mode and it worked for me.

Regards

**Comment by arash-aut** [comment]
Thank you @mavlyutovr
I installed the toolkit in editable mode and it worked for me.

Regards
