### ISSUE TITLE
I want to just t2t service

### ISSUE THREAD

**Issue by juud79** [facebookresearch/seamless_communication#145]
I want to just t2t service (text to text translation)

do i need to load vocoder_name_or_card ??

i want to reduce resource of gpu and improve translation time

when i load no vocoder_name_or_card there is an error
TypeError: Translator.__init__() missing 1 required positional argument: 'vocoder_name_or_card'

  translator = Translator(
        model_name_or_card="seamlessM4T_large",
        vocoder_name_or_card="vocoder_36langs",
        device=device2,
        sample_rate=AUDIO_SAMPLE_RATE,
    )

**Comment by cndn** [comment]
Hey @juud79 - Good point! Right if you just need text output, vocoder is not needed. The Translator is a model wrapper that shows one way to use our model (for all tasks) - but feel free to come up with your own wrapper.
