### ISSUE TITLE
ASR Readability: punctuations and numbers

### ISSUE THREAD

**Issue by zhhl9101** [facebookresearch/seamless_communication#148]
Hello seamless:

From the ASR model output, I did’t see any numbers or punctuations.
For example,
What i want:"帮我读取刘萍1月30日的短信。"
What i got:"帮我读取刘平一月三十日的短信"

Does the model have the features?

Thanks

**Comment by cndn** [comment]
Hey @zhhl9101 - The Chinese output is correct, for your use case you might need a separate library to convert numbers in Chinese to digits (一 -> 1, 三十-> 30).
