### ISSUE TITLE
Question about w2v-BERT 2.0

### ISSUE THREAD

**Issue by aabzaliev** [facebookresearch/seamless_communication#156]
Hello seamless_communication team! First of all, thank you for the excellent work and releasing the code to the public, it's really awesome.

I have a question regarding w2v-BERT 2.0. You mention it in the paper that you got the newer and better version, is there any way to download the weights? I am trying to compare different audio tokenizers and would be curious to play with it. I was able to get an answer for the original w2v-bert [here](https://github.com/facebookresearch/fairseq2/issues/31), and they recommended to ask about w2v-bert 2.0 in your repo. 

Thank you!

Best,
Artem

**Comment by jmp84** [comment]
Hi Artem, the weights are not released but may be in the future.

**Comment by aabzaliev** [comment]
ok, thank you for the reply. Looking forward to it!
