### ISSUE TITLE
UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported class argparse.Namespace

### ISSUE THREAD

**Issue by rishabbjain** [facebookresearch/seamless_communication#159]
85 @staticmethod
     86 def load_model_for_inference(
     87     load_model_fn: Callable[..., nn.Module],
   (...)
     90     dtype: DataType,
     91 ) -> nn.Module:
---> 92     model = load_model_fn(model_name_or_card, device=device, dtype=dtype)
     93     model.eval()
     94     return model
...
--> 809                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
    810         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    811 if weights_only:

UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported class argparse.Namespace

**Comment by cbalioglu** [comment]
Closing for now. Feel free to re-open if the issue persists in fairseq2 v0.2
