### ISSUE TITLE
What is the exact limitations for the audio and text input (ideal and maximum)?

### ISSUE THREAD

**Issue by arash-aut** [facebookresearch/seamless_communication#164]
Dear authors and contributors,
Thank you so much for your great work!
I'm using the toolkit and it's performance is fascinating. However, I would like to get to know more about it's limitations and weaknesses.
Can enyone tell me what is the optimum audio duration for tasks in which input audio is required (i.e., S2ST, S2TT and ASR)? Also, what is the maximum audio duration? 
What about the text input? (optimum and maximum length for the input text for tasks such as T2TT and T2ST)

Thank you in advance!

**Comment by cndn** [comment]
Hey @arash-aut - while absolute max length of audio the model could take depends on the device, it usually way exceeds the "optimal" duration. I would suggest cutting input audios to 15-20 seconds based on silence etc. 

For text input, also I don't have a fixed number as we use subword tokenization where things could differ vastly between languages. With that said, it should be way more robust than audio input - typically you don't need to intentionally cut things to get better translation, but only cutting when OOM is sufficient, if we are only talking about output quality here.

**Comment by arash-aut** [comment]
Dear @cndn Thank you so much for your comprehensive response!

Regards
