### ISSUE TITLE
🦒 colab

### ISSUE THREAD

**Issue by camenduru** [facebookresearch/seamless_communication#18]
Thanks for the project ❤️ I made a colab. 🥳 I hope you like it. https://github.com/camenduru/seamless-m4t-colab

**Comment by rsxdalv** [comment]
> Thanks for the project ❤️ I made a colab. 🥳 I hope you like it. https://github.com/camenduru/seamless-m4t-colab

Good job on the colab!

Though aren't you concerned about the license of this project? I mean especially with derivatives and all.
