### ISSUE TITLE
Demo is not owkring.

### ISSUE THREAD

**Issue by c-spider** [facebookresearch/seamless_communication#190]
sample_input.mp3: 100%|████████████████████████████████████████████| 10.3k/10.3k [00:00<00:00, 59.2MB/s]
sample_input_2.mp3: 100%|███████████████████████████████████████████| 30.6k/30.6k [00:00<00:00, 390kB/s]
Using the cached checkpoint of the model 'seamlessM4T_large'. Set `force=True` to download again.
Killed

**Comment by c-spider** [comment]
it was GPU issue. sorry

**Comment by MarsCaiWORD** [comment]
> it was GPU issue. sorry

Can I ask you how to solve it?

**Comment by c-spider** [comment]
Sure. I don't have GPU and Memory is not enough. So I used medium model, not large one.

This solved my issue, and it's working on my local pc.
