### ISSUE TITLE
Can the speech to speech translation preserve the original speaker's voice?

### ISSUE THREAD

**Issue by drishyakarki** [facebookresearch/seamless_communication#191]

**Comment by c-spider** [comment]
This is really good option.

**Comment by Lidong1211** [comment]
+1

**Comment by drishyakarki** [comment]
I was wondering if we could use the units extracted from audio_to_units.py for this. Is it possible?

**Comment by Lenstack** [comment]
+1

**Comment by masoudpz** [comment]
+1

**Comment by avidale** [comment]
The [SeamlessExpressive](https://github.com/facebookresearch/seamless_communication/blob/main/docs/expressive/README.md) model released in November does preserve many properties of the source voice.
I guess, it fulfills what this issue is asking about.
