### ISSUE TITLE
check_model_dim calls to fairseq2.nn.utils.module need to be removed and modified.

### ISSUE THREAD

**Issue by whitesscott** [facebookresearch/seamless_communication#193]
check_model_dim was recently removed from facebookresearch/fairseq2 repo. Accordingly these 6 calls to that code in seamless_communication need to be modified. I'm just trying to compile and run the facebookresearch/seamless_m4t and fairseq2 with pytorch/cuda.

src/seamless_communication/models/unity/adaptor_block.py
from fairseq2.nn.utils.module import check_model_dim
        check_model_dim(self)
        check_model_dim(self)
        
src/seamless_communication/models/unity/model.py
from fairseq2.nn.utils.module import check_model_dim
        check_model_dim(self)
        check_model_dim(self)

**Comment by cbalioglu** [comment]
Hey @whitesscott, for the time-being please use fairseq2 v0.1.1 with seamless_communication. There have been several API updates in fairseq2 for the upcoming v0.2 release and we will reflect them  to seamless_communication in the near future.
