### ISSUE TITLE
Seamless m4t has diarization?

### ISSUE THREAD

**Issue by Nachuwu** [facebookresearch/seamless_communication#204]
if it has how to use it.

translated_text, wav, sr = translator.predict(
    input='/content/drive/MyDrive/GPI/WAV/1.wav',
    task_str='s2st',
    tgt_lang='spa', # target language
    src_lang='spa', # source language # If you specify this, it will improve the model's result.
    spkr= -1,
)
:param spkr:
        Speaker id for vocoder.

**Comment by avidale** [comment]
No, Seamless does not have diarization. 
You can use some other package (e.g. [pyannote](https://github.com/pyannote/pyannote-audio)) to perform the diarization of your audio, and then feed the resulting segments to Seamless.
