### ISSUE TITLE
Load local model

### ISSUE THREAD

**Issue by Czj1997-02** [facebookresearch/seamless_communication#219]
Thank you for the open source. I would like to inquire. I noticed that the demonstration used the encapsulated method `from seamless_communication.models.inference.translator import Translator`, and the model relies on network pulling. If the model file in the format of '. pt' has already been downloaded, how can it be loaded normally?

**Comment by Czj1997-02** [comment]
Sorry, I get it,  #114 
change path in `seamless_communication\src\seamless_communication\assets\cards` files ， Thanks

**Comment by yangyazhou97** [comment]
hi, even if I change yaml file in "/data/anaconda3/envs/s2s/lib/python3.10/site-packages/seamless_communication/cards/seamlessM4T_v2_large.yaml"
char_tokenizer: "file://data-nvme1n1/yazhou.yang/models/seamless-m4t-v2-large/spm_char_lang38_tc.model"
checkpoint: "file://data-nvme1n1/yazhou.yang/models/seamless-m4t-v2-large/seamlessM4T_v2_large.pt"

I still get error:ValueError: `uri` has the 'file' scheme and must have an absolute pathname, but is 'file://data-nvme1n1/yazhou.yang/models/seamless-m4t-v2-large/seamlessM4T_v2_large.pt' instead.
