### ISSUE TITLE
m4t_predict: error: unrecognized arguments: --ngram-filtering true

### ISSUE THREAD

**Issue by smeteor** [facebookresearch/seamless_communication#241]
i see this in the doc
`Please set --ngram-filtering to True to get the same translation performance as the [demo](https://seamless.metademolab.com/).`

so i use this comman
`CUDA_VISIBLE_DEVICES=2 m4t_predict ./archive_fuxuan_1.wav --task s2st --tgt_lang eng --src_lang cmn --output_path ./archive_fuxuan_1_eng.wav --ngram-filtering true`

but i got an error:
`usage: m4t_predict [-h] [--task TASK] [--tgt_lang TGT_LANG] [--src_lang SRC_LANG] [--output_path OUTPUT_PATH] [--model_name MODEL_NAME] [--vocoder_name VOCODER_NAME]
                   [--text_generation_beam_size TEXT_GENERATION_BEAM_SIZE] [--text_generation_max_len_a TEXT_GENERATION_MAX_LEN_A] [--text_generation_max_len_b TEXT_GENERATION_MAX_LEN_B]
                   [--text_generation_ngram_blocking TEXT_GENERATION_NGRAM_BLOCKING] [--no_repeat_ngram_size NO_REPEAT_NGRAM_SIZE] [--unit_generation_beam_size UNIT_GENERATION_BEAM_SIZE]
                   [--unit_generation_max_len_a UNIT_GENERATION_MAX_LEN_A] [--unit_generation_max_len_b UNIT_GENERATION_MAX_LEN_B] [--unit_generation_ngram_blocking UNIT_GENERATION_NGRAM_BLOCKING]
                   [--unit_generation_ngram_filtering UNIT_GENERATION_NGRAM_FILTERING] [--text_unk_blocking TEXT_UNK_BLOCKING]
                   input
m4t_predict: error: unrecognized arguments: --ngram-filtering true`

whats the right usage?

**Comment by smeteor** [comment]
so i use this command
`CUDA_VISIBLE_DEVICES=2 m4t_predict ./archive_fuxuan_1_16hz.wav --task s2st --tgt_lang eng --src_lang cmn --output_path ./archive_fuxuan_1_eng.wav --unit_generation_ngram_filtering True`
but can not  get the same translation performance as the [demo]

**Comment by TGajanan** [comment]
> sam

I am able to resolve this issue with replacing  "ngram_filtering=true"  >>>>> with "unit_generation_ngram_filtering=True" in predict function
