### ISSUE TITLE
facebook/seamless-expressive is gated

### ISSUE THREAD

**Issue by Shinnonda** [facebookresearch/seamless_communication#245]
While trying the demos, i noticed that the demo expressive is not working cause the model seamless-expressive is private. It its supposed to be like that or it was gated after some time?

**Comment by cocktailpeanut** [comment]
You need to change this line: https://github.com/facebookresearch/seamless_communication/blob/main/demo/m4tv2/app.py#L33

to 

```
snapshot_download(repo_id="facebook/seamless-m4t-v2-large", repo_type="model", local_dir=CHECKPOINTS_PATH)
```

**Comment by abizer** [comment]
fixing this in https://github.com/facebookresearch/seamless_communication/pull/248
