### ISSUE TITLE
Silence produces hallucinations

### ISSUE THREAD

**Issue by ex3ndr** [facebookresearch/seamless_communication#254]
Similar to whisper, this models produce hallucinations when feed with silent audio like this one
[silent.zip](https://github.com/facebookresearch/seamless_communication/files/13597583/silent.zip)

**Comment by elbayadm** [comment]
Yes, @ex3ndr, this is a known issue of encoder-decoder models for ASR/Speech-to-text. One way to avoid these hallucinations is to use a Voice Activity Detector (VAD) model to either skip generating outputs for all-silence inputs or chunk audios with long silences in the middle.

**Comment by ex3ndr** [comment]
Thank you, I ended up with a similar idea and now training VAD to use efficiently

**Comment by elbayadm** [comment]
Would you mind sharing your script for efficiently using VAD with seamless models?
