### ISSUE TITLE
is it typo in UnitExtractor? `self.collate = Collater(pad_value=2, pad_to_multiple=2)`

### ISSUE THREAD

**Issue by seastar105** [facebookresearch/seamless_communication#255]
https://github.com/facebookresearch/seamless_communication/blob/91918a642e2b0339823350e604a5e5419de5de2c/src/seamless_communication/models/unit_extractor/unit_extractor.py#L37-L59

UnitExtractor collates batch using `Collater(pad_value=2, pad_to_multiple=2)`. it seems unusual to use pad_value as 2.  is it correct? or typo?

**Comment by kauterry** [comment]
You are right, it is incorrect, I fix it in https://github.com/facebookresearch/seamless_communication/pull/251
