### ISSUE TITLE
We tried Seamless for VideoDubber.ai

### ISSUE THREAD

**Issue by Souvic** [facebookresearch/seamless_communication#291]
Hi,
We tried Seamless for [VideoDubber.ai](https://www.videodubber.com/) today to provide one-click video translation with voice cloning to top 30+ languages of the world by native speakers for free without any watermark.
The results were better with step by step translation than seamless. As [VideoDubber.ai](https://www.videodubber.com) strives to provide the most accurate translation for videos after checking each available technology against a internal dataset of diverse videos, we will not be using seamless for now. We look forward to other versions of seamless later in future which may work much better.

**Comment by avidale** [comment]
Thanks a lot for the feedback!
