### ISSUE TITLE
Are SeamlessM4T v2, SeamlessExpressive, and SeamlessStreaming under an MIT license and therefore free for commercial use?

### ISSUE THREAD

**Issue by troublesprouter** [facebookresearch/seamless_communication#297]
Found this but seeking confirmation: https://github.com/facebookresearch/seamless_communication/blob/main/MIT_LICENSE

**Comment by cndn** [comment]
Unfortunately, these models are NOT allowed for commercial use now. As stated in README (https://github.com/facebookresearch/seamless_communication?tab=readme-ov-file#license), only certain components and code are MIT licensed.
