### ISSUE TITLE
Where can I find the source code for Watermarking?

### ISSUE THREAD

**Issue by jishengpeng** [facebookresearch/seamless_communication#311]
The original paper mentions the inclusion of speech watermarking techniques in Section 8.4. However, I have been unable to locate the corresponding source code and checkpoint. I would like to inquire whether the authors have any plans to release the open-source code pertaining to speech watermarking.

**Comment by avidale** [comment]
The source code for watermarking was released as https://github.com/facebookresearch/audioseal.
