### ISSUE TITLE
m4t_predict: command not found

### ISSUE THREAD

**Issue by upadrasta84** [facebookresearch/seamless_communication#36]
Unable to find the m4t_predict command. Can you please advise. 

ubuntu 20.04.1

pip --version
pip 23.0.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)

**Comment by upadrasta84** [comment]
please ignore.. this was an issue on my side.

**Comment by Azam2107** [comment]
Hi, how did you solve this issue?

**Comment by YRH0** [comment]
Hi, how did you solve this issue?

**Comment by YRH0** [comment]
> Hi, how did you solve this issue?

I forget activating Conda environment.

**Comment by shiccup** [comment]
I am having this issue but my conda environment is activated I assume it's a path issue, but I am not really sure. I am new to using Linux subsystems on windows.
