### ISSUE TITLE
Commercial License

### ISSUE THREAD

**Issue by upadrasta84** [facebookresearch/seamless_communication#38]
https://github.com/facebookresearch/seamless_communication/issues/28

I agree with this. Please make it a commercial license. LLaMa 2 is now everywhere. Hope this model can have similar success. without the commercial license, there is not much use of this model. I support @bitnom 's comments in the above issue. Since it is closed, i am raising a new one to get some support on this.

**Comment by ejkitchen** [comment]
I hope OPENAI makes a Whisper 3 and makes this a non-issue.

**Comment by zachNA2** [comment]
+1

**Comment by jmp84** [comment]
reopened #28
