### ISSUE TITLE
Is it possible to generate NBest list (ASR)?

### ISSUE THREAD

**Issue by cyfer0618** [facebookresearch/seamless_communication#39]
Can someone share the part or code where we can generate the N-best list for ASR?

**Comment by cndn** [comment]
IIUC this needs fairseq2 text generator to expose N-best generation results from text generator. Now it only returns the the top hypothesis. (https://github.com/fairinternal/fairseq2/blob/255522368205ae68f1021d5b130d21f79ebd30ba/src/fairseq2/generation/text.py#L80). So if you'd like to achieve this now you could hack the fairseq2 code to have it return remaining hypothesis when beam search ends, and propagate from there.
