### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by sankalp-25** [facebookresearch/seamless_communication#41]
Can I run this on CPU only, in a windows machine?

**Comment by grigio** [comment]
+1 but cpu on linux, is there a way to run it?

**Comment by Bassir** [comment]
Would also be nice to see if it can be ran on CoreML

**Comment by kauterry** [comment]
https://github.com/facebookresearch/seamless_communication/pull/54 fixes CPU inference on a Linux machine. As for Windows support, echoing from the README:
> At this point fairseq2 has a confirmed support only for Linux and macOS. Pre-built packages are only available for Linux (macOS is planned).
