### ISSUE TITLE
!!!!!!!!!Bug  RuntimeError: expected scalar type Half but found Float $$$$$$$$$$

### ISSUE THREAD

**Issue by developeranalyser** [facebookresearch/seamless_communication#414]
%run  /content/seamless_communication/cli/m4t/finetune/finetune.py \
   --mode TEXT_TO_SPEECH \
   --train_dataset /content/my_m4t_dataset/train_manifest.json  \
   --eval_dataset /content/my_m4t_dataset/validation_manifest.json \
   --learning_rate 1e-6 \
   --warmup_steps 100 \
   --max_epochs 5 \
   --patience 5 \
   --save_model_to /content/my_m4t_dataset/checkpoint1.pth
#  --model_name seamlessM4T_v2_large \

**Comment by zrthxn** [comment]
Fixed in #400

**Comment by zrthxn** [comment]
@mavlyutovr This was the autocast issue I had, which was fixed.

**Comment by developeranalyser** [comment]
> @mavlyutovr  
why now i have this bug 
in latest main branch codes

**Comment by developeranalyser** [comment]
why now i have this bug
in latest main branch codes

**Comment by developeranalyser** [comment]
CUDA out of memory. Tried to allocate 238.00 MiB. GPU 0 has a total capacity of 14.75 GiB of which 161.06 MiB is free. Process 121503 has 14.59 GiB memory in use. Of the allocated memory 14.39 GiB is allocated by PyTorch, and 61.74 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



> @mavlyutovr This was the autocast issue I had, which was fixed.

**Comment by Angelalilyer** [comment]
hello! I met this bug, too. could you please tell me how to fix it?  Which code file should I change？ thank you very much!

**Comment by zrthxn** [comment]
@Angelalilyer @developeranalyser You can use my branch [`zrthxn:fix/finetune-precision-autocast`](https://github.com/zrthxn/seamless_communication/tree/fix/finetune-precision-autocast) for the time being until the PR gets merged.  
```
git switch -c fix/finetune-precision-autocast
git pull git@github.com:zrthxn/seamless_communication.git fix/finetune-precision-autocast
```

**Comment by Angelalilyer** [comment]
> @Angelalilyer @developeranalyser ~You can use my branch [`zrthxn:fix/finetune-precision-autocast`](https://github.com/zrthxn/seamless_communication/tree/fix/finetune-precision-autocast) for the time being until the PR gets merged.~ The PR was merged, the latest version should work fine now

Thank you very much, i also encountered "cuda out of memory" when using new code. May I know how much memory is sufficient

**Comment by zrthxn** [comment]
@Angelalilyer For me usually a Google Colab A100 GPU works fine.
