### ISSUE TITLE
Error with GPU 40GB !!!!!!!!!

### ISSUE THREAD

**Issue by developeranalyser** [facebookresearch/seamless_communication#421]
i have 40GB gpu vram and id get error CUDA out of memory.
with A100 gpu

for fine tune how much gpu vram needed ?
id use colab pro its possible ?

Isn't it ridiculous?

TnkU

**Comment by Angelalilyer** [comment]
I also encountered this issue while using the new code. May I ask if you have resolved this issue

**Comment by developeranalyser** [comment]
> I also encountered this issue while using the new code. May I ask if you have resolved this issue

not now  _  I'm trying...... :(

**Comment by developeranalyser** [comment]
> I also encountered this issue while using the new code. May I ask if you have resolved this issue

do you can solve this ?

**Comment by zrthxn** [comment]
The large version will crash out even on Colab A100. Maybe trying using the medium version.

**Comment by developeranalyser** [comment]
> The large version will crash out even on Colab A100. Maybe trying using the medium version.

Does you have a better idea?
I want to use V2 features and functions for 3 limited languages
Can you kindly guide me how to ????

**Comment by developeranalyser** [comment]
> The large version will crash out even on Colab A100. Maybe trying using the medium version.

How can I use the features of v2 with less volume for specific languages to get good results like v2?

Do you know a better model for this job than V2?

**Comment by WandererGuy** [comment]
> i have 40GB gpu vram and id get error CUDA out of memory. with A100 gpu
> 
> for fine tune how much gpu vram needed ? id use colab pro its possible ?
> 
> Isn't it ridiculous?
> 
> TnkU

i have to ```--batch_size 1``` and ```--model_name seamlessM4T_medium``` to finetune on RTX3090 with 24 GB , it took over bit 18GB. at least it can finetune now.
using ```--model_name seamlessM4T_v2_large``` will cause me out of cuda memory with this gpu RTX3090 vram) , 
Tip: along with let ```--batch_size 1``` and ```--model_name seamlessM4T_medium```, you can also NOT include this in your command, which will reduce about 6GB vram for you too : 
```
torchrun \
   --rdzv-backend=c10d \
   --rdzv-endpoint=localhost:4060 \
   --nnodes=1 \
   --nproc-per-node=1  \
   --no-python \ 
```
. so my command is for example: 
```  
m4t_finetune \
   --mode SPEECH_TO_TEXT \
   --train_dataset $DATASET_DIR/train_manifest.json  \
   --eval_dataset $DATASET_DIR/validation_manifest.json \
   --learning_rate 1e-6 \
   --warmup_steps 100 \
   --max_epochs 10 \
   --patience 5 \
   --model_name seamlessM4T_medium \
   --save_model_to $DATASET_DIR/checkpoint.pt \
   --batch_size 1
```
