### ISSUE TITLE
Predict using code

### ISSUE THREAD

**Issue by Talhavaival1** [facebookresearch/seamless_communication#43]
I wanted to ask is it possible to run inference using code , 

I am tryting to do S2ST but i dont know what to put in speech units part in the code given below 

```
wav, sr = translator.synthesize_speech(<speech_units>, <tgt_lang>)

# Save the translated audio generation.
torchaudio.save(
    <path_to_save_audio>,
    wav[0].cpu(),
    sample_rate=sr,
)

```

**Comment by Mortimerp9** [comment]
https://github.com/facebookresearch/seamless_communication/blob/main/src/seamless_communication/models/inference/translator.py#L150 has more details

**Comment by Talhavaival1** [comment]
I wanted to know what should I put in wav, sr = translator.synthesize_speech(<speech_units>, <tgt_lang>) , speech units part

**Comment by l4b4r4b4b4** [comment]
yeah I am stumbling over tihs one as well. And when I plug the tensor response from `predict` as follows, it does generate a small 2 sec audio, but without any content. But I just started playing around 2 hours ago ...
```python
translated_text, wav, sr = translator.predict(
        content, mode, target_lang, src_lang=source_lang
    )

    # Save the translated audio generation.   
    # wav, sr = translator.synthesize_speech(wav, "eng")
    unique_filename = str(uuid.uuid4())  # Generate a UUID and convert it to a string
    file_extension = ".wav"  # Replace with the desired file extension
    file_path = os.path.join(folder_path, unique_filename + file_extension)

    # # Save the translated audio generation.
    torchaudio.save(
        file_path,
        wav[0].cpu(),
        # TODO test gpu
        # wav[0].cpu(),
        sample_rate=sr,
    )
```
