### ISSUE TITLE
The large version will crash out even on Colab A100. Maybe trying using the medium version.

### ISSUE THREAD

**Issue by developeranalyser** [facebookresearch/seamless_communication#433]
The large version will crash out even on Colab A100. Maybe trying using the medium version.

_Originally posted by @zrthxn in https://github.com/facebookresearch/seamless_communication/issues/421#issuecomment-2070129853_
            

Does anyone have a better idea?
I want to use V2 features and functions for 3 limited languages
Can you kindly guide me how to ????

**Comment by v-tuenv** [comment]
If you use the asr-pipeline or s2t-pipeline, you will get the OOM. The paper mentioned about streamming, but it's not. The model will accumulate all frame of the speech to the model when we reach the new ones. 
For example: 
First-chunk 320ms -> model will use 320ms for prediction
Second-chunk 320ms -> model will use 320ms from previous + 320ms current to make the prediction.
And so on.... 
------------
So we don't have upper boundary memory cuda to make the model safe in memory. You should break the audio into small chunks, and inference separately.
I don't see the t2s part of the model, but maybe similarity with your issue.
