### ISSUE TITLE
Fine Tune Not work for text to speech ???????????????????????????????

### ISSUE THREAD

**Issue by developeranalyser** [facebookresearch/seamless_communication#438]
File "/content/my_seamless_communication/src/seamless_communication/cli/m4t/finetune/trainer.py", line 127, in forward
    raise NotImplementedError(
NotImplementedError: T2U finetuning implemented only for UnitYT2UModel

**Comment by developeranalyser** [comment]
its work  ; )

**Comment by Paulmzr** [comment]
does it work for UnitYT2UNAR in UnitY**2**?

**Comment by developeranalyser** [comment]
UnitYT2UModel  must be added in ft

**Comment by developeranalyser** [comment]
> UnitYT2UNAR

must add to model in ft before run()

**Comment by developeranalyser** [comment]
no
have you any way ?
