### ISSUE TITLE
Update install instructions for libsndfile

### ISSUE THREAD

**Issue by cbalioglu** [facebookresearch/seamless_communication#44]
Let us mention that users can (preferably) install libsndfile using their system package manager without resorting to Conda if they have sudo access.

**Comment by jborut** [comment]
Also, would someone please explain in more details how to install libsndfile and make it work? I followed this closed issue here https://github.com/facebookresearch/seamless_communication/issues/42 but for the life of me I can't figure out how to make it work.

**Comment by skanda1005** [comment]
Try using a python venv and then apt-get libsndfile1
```
python3 -m venv <env-name>
source <env-name>/bin/activate
pip install .
apt-get install -y libsndfile1
```
