### ISSUE TITLE
text to text not showing even as an option m4t_predict: error: argument --task: invalid choice: 'T2TT' (choose from 'ASR', 'S2ST', 'S2TT')

### ISSUE THREAD

**Issue by gloomiebloomie** [facebookresearch/seamless_communication#452]
Text to text is not available for some reason for task. The instructions in the read me don't work. 
 m4t_predict "Hello how are you doing?" --task T2TT --tgt_lang
arz --src_lang eng --model_name seamlessM4T_v2_large
usage: m4t_predict [-h] [--task {ASR,S2ST,S2TT}] [--tgt_lang TGT_LANG] [--src_lang SRC_LANG]
                   [--output_path OUTPUT_PATH] [--model_name MODEL_NAME] [--vocoder_name VOCODER_NAME]
                   [--text_generation_beam_size TEXT_GENERATION_BEAM_SIZE]
                   [--text_generation_max_len_a TEXT_GENERATION_MAX_LEN_A]
                   [--text_generation_max_len_b TEXT_GENERATION_MAX_LEN_B]
                   [--text_generation_ngram_blocking TEXT_GENERATION_NGRAM_BLOCKING]
                   [--no_repeat_ngram_size NO_REPEAT_NGRAM_SIZE]
                   [--unit_generation_beam_size UNIT_GENERATION_BEAM_SIZE]
                   [--unit_generation_max_len_a UNIT_GENERATION_MAX_LEN_A]
                   [--unit_generation_max_len_b UNIT_GENERATION_MAX_LEN_B]
                   [--unit_generation_ngram_blocking UNIT_GENERATION_NGRAM_BLOCKING]
                   [--unit_generation_ngram_filtering UNIT_GENERATION_NGRAM_FILTERING]
                   [--text_unk_blocking TEXT_UNK_BLOCKING]
                   input
m4t_predict: error: argument --task: invalid choice: 'T2TT' (choose from 'ASR', 'S2ST', 'S2TT')
 m4t_predict "Hello how are you doing?" --task T2TT --tgt_lang arz --src_lang eng
usage: m4t_predict [-h] [--task {ASR,S2ST,S2TT}] [--tgt_lang TGT_LANG] [--src_lang SRC_LANG]
                   [--output_path OUTPUT_PATH] [--model_name MODEL_NAME] [--vocoder_name VOCODER_NAME]
                   [--text_generation_beam_size TEXT_GENERATION_BEAM_SIZE]
                   [--text_generation_max_len_a TEXT_GENERATION_MAX_LEN_A]
                   [--text_generation_max_len_b TEXT_GENERATION_MAX_LEN_B]
                   [--text_generation_ngram_blocking TEXT_GENERATION_NGRAM_BLOCKING]
                   [--no_repeat_ngram_size NO_REPEAT_NGRAM_SIZE]
                   [--unit_generation_beam_size UNIT_GENERATION_BEAM_SIZE]
                   [--unit_generation_max_len_a UNIT_GENERATION_MAX_LEN_A]
                   [--unit_generation_max_len_b UNIT_GENERATION_MAX_LEN_B]
                   [--unit_generation_ngram_blocking UNIT_GENERATION_NGRAM_BLOCKING]
                   [--unit_generation_ngram_filtering UNIT_GENERATION_NGRAM_FILTERING]
                   [--text_unk_blocking TEXT_UNK_BLOCKING]
                   input
m4t_predict: error: argument --task: invalid choice: 'T2TT' (choose from 'ASR', 'S2ST', 'S2TT')

**Comment by jasonyang-ytl** [comment]
Try adding the following into `src/seamless_communication/cli/m4t/predict/predict.py`
`parser.add_argument(
        "--task", 
        type=str, 
        choices=["ASR", "S2ST", "S2TT", "T2TT"],
        help=(
            "* `ASR` -- automatic speech recognition (transcription);"
            "* `S2ST` -- speech to speech translation;"
            "* `S2TT` -- speech to text translation;"
            "* `T2TT` -- text to text translation"
        )
    )`

**Comment by liuhao0813** [comment]
@jasonyang-ytl Very well, solved in your own way, thank you.

**Comment by kulogix** [comment]
For Text-to-Speech Translation, which is also missing from the latest CLI code:

parser.add_argument( "--task", type=str, choices=["ASR", "S2ST", "S2TT", "T2TT", "T2ST"], help=( "* ASR -- automatic speech recognition (transcription);" "* S2ST -- speech to speech translation;" "* S2TT -- speech to text translation;" "* T2TT -- text to text translation" "* T2ST -- text to speech translation" ) )

Note: I also had to use uppercase when specifying task...

seamlessm4t % m4t_predict "Well, hello there handsome" --task T2ST --tgt_lang fra --src_lang eng --output_path handsome-fra.mp3 --model_name seamlessM4T_v2_large
