### ISSUE TITLE
Specify model path for offline loading

### ISSUE THREAD

**Issue by jgwinnup** [facebookresearch/seamless_communication#50]
Is it possible to specify a path for the model checkpoint to facilitate offline loading?

**Comment by cndn** [comment]
Hey @jgwinnup - Good call, for now you could override path in asset cards e.g. https://github.com/facebookresearch/seamless_communication/blob/main/src/seamless_communication/assets/cards/seamlessM4T_large.yaml#L10, with a prefix "file://" to indicate local path.

Also paths are cached so you should only need to download it once anyway.

**Comment by jgwinnup** [comment]
Thanks for the pointer - when I specify a file:// URI I get the following error:
```
fairseq2.assets.card.AssetCardError: The value of the field 'checkpoint' of the asset card 'seamlessM4T_large' must be a valid URI, but is 'file:///foo/bar/seamless-m4t-large/multitask_unity_large.pt' instead.
```
I can work around this by starting up a python http.server and serve the file locally, but it would be nice to have proper file:// URI support.

**Comment by cndn** [comment]
Hey @jgwinnup double checking the logic here it should work https://github.com/facebookresearch/fairseq2/blob/main/src/fairseq2/assets/download_manager.py#L132. Could you print out pathname here and see if it's expected?

**Comment by Akira4ever** [comment]
> fairseq2.assets.card.AssetCardError: The value of the field 'checkpoint' of the asset card 'seamlessM4T_large' must be a valid URI, but is 'file:///foo/bar/seamless-m4t-large/multitask_unity_large.pt' instead.

Maybe this should be  'file://foo/bar/seamless-m4t-large/multitask_unity_large.pt', with only two '/' after "file:"?

**Comment by efwfe** [comment]
~/.cache/torch/hub/fairseq2/assets/checkpoints/43b8b74ddb6b784
86fb47754
Get this path when i download the file, try move the pt file to this path may be helpful.

**Comment by jgwinnup** [comment]
Hi - I filed a similar issue on fairseq2 #facebookresearch/fairseq2#6, looks like the issue is that I was specifying an absolute path with a leading slash (e.g. checkpoint: 'file:///foo/bar/model.pth') but was asked to just use two slashes (checkpoint: 'file://foo/bar/model.pth') and that worked.
