### ISSUE TITLE
Question regarding MMS and seamless

### ISSUE THREAD

**Issue by HeChengHui** [facebookresearch/seamless_communication#506]
[MMS](https://github.com/facebookresearch/fairseq/tree/main/examples/mms)

if i am looking for purely STT performance, which one is better? mms or seamless?

**Comment by avidale** [comment]
Seamless was never intended for pure TTS. You can hack it into synthesizing speech (by doing text-to-speech translation into the same language), but there are absolutely no guarantees that it won't behave weirdly.
 
Also, note that Seamless can produce speech outputs in only ~37 languages, whereas MMS speech synthesis covers about 1000 languages.

**Comment by HeChengHui** [comment]
@avidale 
Thank you for the comment. 
I actually wanted to ask about Speech to Text (STT) performance.

**Comment by avidale** [comment]
Oh, sorry. I am used to refer to it as ASR (automatic speech recognition).
According to the [SeamlessM4T paper](https://arxiv.org/abs/2308.11596), Table 16, when evaluating on 54 languages from FLEURS, SeamlessM4T models outperform pure CTC decoding with MMS models in terms of WER, but when language models are added to MMS, MMS has even lower WER than Seamless.

<img width="817" alt="image" src="https://github.com/user-attachments/assets/8486d4fc-3e7f-4129-ba27-3ba8b4a264a4">

**Comment by HeChengHui** [comment]
@avidale 
The paper quoted seems to be seamless V1? 
what about V2 that is linked on the homepage?  [paper](https://ai.meta.com/research/publications/seamless-multilingual-expressive-and-streaming-speech-translation/), it seems like the WER is better than whisperV3-large. But what about MMS?

**Comment by avidale** [comment]
Based on the Table 7 in the v2 paper, the WER of SeamlessM4T-Large v2 on FLEURS-54 is 19.1: still between the WER of MMS-noLM (31.0) and MMS-CCLM (18.7).
<img width="999" alt="image" src="https://github.com/user-attachments/assets/2879f67f-5f28-48fc-ba7c-0f84fb518f90">
