### ISSUE TITLE
seamless-m4t-v2-large can only partially transcribe

### ISSUE THREAD

**Issue by jollyfish-cjy** [facebookresearch/seamless_communication#508]
Hi, sorry for bothering you. I tried to use seamless-m4t-v2-large for testing ASR inference (with 🤗 Transformers) on my own datasets. But  I only got partial transcriptions for audios. For example, the reference sentence is 

> Mr President, Excellencies, dear colleagues, I have the honor to deliver this statement on behalf of the Group of Western European and Other States. Mr President, nuclear non-proliferation and nuclear disarmament have been among the key priorities of the United Nations since the establishment of the organization in 1945. An important element that lies at the core of these objectives is the ban of all nuclear weapon

And here is what I got through seamless-m4t:

> Mr President, I have the honour to deliver this statement on behalf of the Group of the European People's Party. Nuclear non proliferation and nuclear disarmament have been among the key priorities of the United Nations since the establishment of the Organization in 1945. An important element that lies at the core of these objectives is the ban

Looks like model skip some words or even sentences. I don't know what happened here. The original audio of this example is wav format and its duration is 29 sec.

And here is my code:

```
import os

import pandas as pd
from config import Config as cfg

import torchaudio
from transformers import AutoProcessor, SeamlessM4Tv2ForSpeechToText
from tqdm import tqdm

processor = AutoProcessor.from_pretrained("facebook/seamless-m4t-v2-large")
model = SeamlessM4Tv2ForSpeechToText.from_pretrained("facebook/seamless-m4t-v2-large")

df = pd.read_csv(cfg.csv_file, header=0)

predicts = []
for idx, row in tqdm(df.iterrows()):
    audio_path = os.path.join(cfg.file_path, row["en_audio_segment_path"][16:].replace("/", "\\"))
    print(audio_path)
    audio, orig_freq = torchaudio.load(audio_path)
    audio = torchaudio.functional.resample(audio, orig_freq=orig_freq, new_freq=16_000)

    audio_inputs = processor(audios=audio, return_tensors="pt")
    text_array_from_audio = model.generate(**audio_inputs, tgt_lang="eng")[0].tolist()
    transcript = processor.decode(text_array_from_audio, skip_special_tokens=True)
    predicts.append(transcript)

df["predictions"] = predicts
df.to_csv("seamless-m4t-v2-large-test.csv", index=False)

```

Could anyone please help me deal with this problem? Thank you so much!

**Comment by minh-nguyenhoang** [comment]
Hi did you solve this problem?
