### ISSUE TITLE
On-device run: quantization?

### ISSUE THREAD

**Issue by dennislysenko** [facebookresearch/seamless_communication#53]
Hey guys,

Great work! 
I was curious about the on device readme: 
https://github.com/facebookresearch/seamless_communication/blob/main/docs/m4t/on_device_README.md

The disk size for each of these is a little large to package with a use case like an app download. 
Any idea if say 4x quantization is possible to get medium down to ~150MB from ~600MB? Or are these already quantized?

**Comment by Bassir** [comment]
Some of the whisper cpp apps on iOS are quite large. What’s wrong w 600MB?

**Comment by cndn** [comment]
Hey @dennislysenko thanks for the feedback! Yes we think 600MB IS considered large on device. This is with fp16 inference. There are several lines of investigation on both engineering/research side for us now, sharing a few:
(1) int8 quantization
(2) Tackling overhead in model overhead. Ideally storing 235M parameters in fp16 would take ~470MB but now we have more than that. 
(3) Careful "scaling down" the model without hurting quality by distillation etc.

**Comment by cndn** [comment]
For (2) we fixed some issues and s2t on-device model is back to 480M as expected now. Updated checkpoint link feel free to try again @dennislysenko
