### ISSUE TITLE
Generate models by picking tasks and languages

### ISSUE THREAD

**Issue by a8nova** [facebookresearch/seamless_communication#56]
If we could bundle on-device models with languages and tasks of our choice that would be great.

For example: 
Task: ASR
Languages: English and African languages

**Comment by cndn** [comment]
Hey @a8nova thanks for the suggestion, we will consider language pack, but haven't started actively working on that.

**Comment by alshenkute** [comment]
Thank you @cndn . If possible, i would like to contribute by making this possible but I will need pointers. Thanks

**Comment by a8nova** [comment]
Thank you @cndn . If possible, i would like to contribute by making this possible but I will need pointers. Thanks
