### ISSUE TITLE
seamless communication on raspberry pi 4 or Nvidia Jetson

### ISSUE THREAD

**Issue by kiashann** [facebookresearch/seamless_communication#66]
Is it possible to use pretrained model for inference on raspberry pi 4 or Nvidia Jetson?
What is the latest hardware requirements to use on boards?
Anyone can help me, or do you have such experience to use pretrained model like this on boards?

**Comment by Juan1108888** [comment]
I also want to know!
For small models, maybe try

**Comment by astrowar** [comment]
I tested it on a jetson orin nano. The medium and large models exceed the amount of memory available.
The small model takes 47s to translate a 5s audio and uses 2GB (inference only, the model loads is fast < 7s). The audio output has good quality. The translation gets a little sluggish on the first word in some tests. but the overall result is good in the two languages I tested.
To work you need to add the resample to 16Khz in the input

**Comment by Juan1108888** [comment]
> 
How ASR and T2ST?

**Comment by cndn** [comment]
Hey @kiashann - we don't have active plan to support specific hardwares. If you're able to get our project working on a new hardware platform or have insights on improvements, would be appreciated if you could contribute knowledge!

**Comment by sytpb** [comment]
how about the raspberry PI5 , focus on it .
