### ISSUE TITLE
Install problem on MAC Pro M1

### ISSUE THREAD

**Issue by PierreVannier** [facebookresearch/seamless_communication#68]
It seems their is a problem with fairseq2 install that blocks installation.
Seems related to [this one](https://github.com/facebookresearch/fairseq2/issues/1)

**Comment by Mortimerp9** [comment]
fairseq2 does not have a package for macos (intel or M1) yet, but you should be able to follow the manual build instructions of fairseq2: https://github.com/fairinternal/fairseq2#install-from-source

You might want to follow along on the fairseq2 repo if you want.

**Comment by PierreVannier** [comment]
Thanks @Mortimerp9 ! I’ll look into that. 👍🏻

**Comment by changeling** [comment]
@Mortimerp9 Could you re-open this issue? The install from source process  on Apple Silicon doesn't seem to work.

```
MacBook Pro
MacOS 13.4.1
M1 Pro
16GB
Python 3.11
```

Starting with a fresh venv created by `python3.11 -m venv venv` and a freshly cloned `fairseq2`, following the procedure presented at https://github.com/facebookresearch/fairseq2#install-from-source,  I see the following:

```
(venv)  fairseq2 % pip install .
Processing /Volumes/Project_Drive/seamless_communication_playground/fairseq2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.0
```

**Comment by freedomtan** [comment]
you got to build the fairseq2n, which is the native code part of the fairseq2, first

How I built it:
```
1. cd ${ROOT_OF_FAIRSEQ2}/fairseq2n
2. mkdir build
3. cd build  # now we are in ${ROOT_OF_FAIRSEQ2}/fairseq2n/build
4. cmake .. # with tbb 2021.q or later, libsndfile, and other dependencies installed, this should work
5. make install # or copy libfairseq2n.*.dylib in src/fairseq2n/ to the right lib path
6. cd ..
7. python setup.py bdist_wheel # there should be a pip wheel in dist 
8. pip install $THE_PIP_WHEEL_FILE_YOU_BUILD

````

**Comment by ponymushama** [comment]
> you got to build the fairseq2n, which is the native code part of the fairseq2, first
> 
> How I built it:
> 
> ```
> 1. cd ${ROOT_OF_FAIRSEQ2}/fairseq2n
> 2. mkdir build
> 3. cd build  # now we are in ${ROOT_OF_FAIRSEQ2}/fairseq2n/build
> 4. cmake .. # with tbb 2021.q or later, libsndfile, and other dependencies installed, this should work
> 5. make install # or copy libfairseq2n.*.dylib in src/fairseq2n/ to the right lib path
> 6. cd ..
> 7. python setup.py bdist_wheel # there should be a pip wheel in dist 
> 8. pip install $THE_PIP_WHEEL_FILE_YOU_BUILD
> ```

```
cmake ..

CMake Error at CMakeLists.txt:16 (message):
  It looks like you are in a Conda environment, but the compiler packages are
  not installed.  Please run `conda install -c conda-forge compilers` first.


-- Configuring incomplete, errors occurred!
```

I meet this.

I have followed [Install From Source (C++/CUDA) — fairseq2 0.1.0 documentation](https://facebookresearch.github.io/fairseq2/stable/installation/from_source) this link to install dependencies.
