### ISSUE TITLE
Finetuning on custom dataset for ASR

### ISSUE THREAD

**Issue by Incarceronn** [facebookresearch/seamless_communication#70]
Hi, I have a custom dataset of one language with a csv files of the labels and filepaths, as well as a directory of audio files. 

Can anyone suggest what steps they took to finetune the model (especially for a monolingua ASR task), as I am unclear how to prepare the local dataset given that I would not have the manifest and many other details present in the fleurs dataset in the example finetuning

Any help is greatly appreciated!

**Comment by mavlyutovr** [comment]
@Incarceronn I would suggest to implement a lightweight alternative to Speech2SpeechFleursDatasetBuilder and use it in scripts/m4t/finetune/dataset.py. The ASR specific will be that source and target in LangPairSample will be equal (pointing to the same MultimodalSample), and each MultimodalSample will have the following field values:

    id - uniq identifier of the sample
    lang - language code of the dialect
    text - transcription of the audio sample
    audio_local_path - local path to the audio sample
    waveform = None
    sampling_rate = None
    units: List[int] - list of units produced by UnitSpeechTokenizer from the audio sample

**Comment by Gxhappiness** [comment]
Hi,
I have the same problem. Have u addressed the issue? Such as the data preparation and the finetuning process.
