### ISSUE TITLE
[S2ST] Using Bible Audio Translations & Text Translations for Low Resource Languages

### ISSUE THREAD

**Issue by allandclive** [facebookresearch/seamless_communication#71]
For low resource language coverage, is it practical to use bible audio translations (For STST) & also Text translations, to create a parallel dataset?  My major focus is Speech to Speech Translation

**Comment by jmp84** [comment]
@allandclive it's possible. Here is some related work: https://arxiv.org/abs/1907.12895 and https://arxiv.org/abs/2305.13516
