### ISSUE TITLE
The translation effect is not as good as the official

### ISSUE THREAD

**Issue by 823863429** [facebookresearch/seamless_communication#84]
For the same sentence, the official translation is much better. Using the Quick Start method, the translation is repetitive and the meaning is not accurate enough. All use the model of seamlessM4T_large

Official translation: I want to live as a couple, to be together, to work together, to suffer together, to live in the same house, to eat three meals a day, to be happy, I know it's not easy,

Translate results by myself: I want a couple to live together, to work together, to work together, to suffer together, to live together, to live together, to live together, to live together, to live together, to live together.

**Comment by YanziSun** [comment]
yes

**Comment by ghiaccio77** [comment]
yes

**Comment by kauterry** [comment]
Please set this argument to True to get the same translation performance as the demo: https://github.com/facebookresearch/seamless_communication/blob/main/scripts/m4t/predict/predict.py#L50-L55
