### ISSUE TITLE
#solved ValueError: `lang` 

### ISSUE THREAD

**Issue by BlockSats** [facebookresearch/seamless_communication#86]
Hello, this is the first time I'm testing "Seamless m4t" because it totally matches one of my needs.
I tried to use it with Google Colab and encountered a language error. I gave the instruction "fr" but it doesn't seem to work.
I haven't found the answer to my problem.

Here's the command line I gave it :
`!m4t_predict /content/drive/MyDrive/content/drive/MyDrive/m4t/orderblock.wav s2st fr --output_path /content/drive/MyDrive/content/drive/MyDrive/m4t/`

You'll have gathered that I'm looking to move on to a French translation.
Thanks in advance

**Comment by BlockSats** [comment]
I found for the translation, you have to use "fra"

However, I'm having trouble with the length  :
ValueError: The input sequence length must be less than or equal to the maximum sequence length (4096), but is 107358 instead.

I haven't seen any mention of limitations. How can I get around this?
A paid version ?

**Comment by kauterry** [comment]
Please check https://github.com/facebookresearch/seamless_communication/issues/77
