### ISSUE TITLE
maximum sequence length (4096)

### ISSUE THREAD

**Issue by BlockSats** [facebookresearch/seamless_communication#87]
I'm having trouble with the length :
ValueError: The input sequence length must be less than or equal to the maximum sequence length (4096), but is 107358 instead.

I haven't seen any mention of limitations. How can I get around this?
A paid version ?

**Comment by BlockSats** [comment]
I wanted to use it on hour-long videos, but I think I was a little too quick to rejoice.

**Comment by kauterry** [comment]
Please check https://github.com/facebookresearch/seamless_communication/issues/77

**Comment by BlockSats** [comment]
Okay, thanks for the tip. 
So can you confirm that this solution will make it possible to work on videos of any length?
But the result will be several output files?
Will the maximum length be modified in the future? 
Thx
