### ISSUE TITLE
Using finetuned model for inference

### ISSUE THREAD

**Issue by Incarceronn** [facebookresearch/seamless_communication#93]
I have trained a model and have the checkpoint.pt file, but am unable to use it for inference (ASR)

I don't see an option on the Translator object to specify the path to use when using m4t large for example.

Anyone have solutions for this? I'm sure it's just a one liner that I'm missing somewhere.

**Comment by MenggeLiu** [comment]
You can try to print and view the .pt file saved after fine-tuning. I found that the key of the state_dict and the key of the model parameters do not match. I successfully loaded the fine-tuned model by modifying the code for saving and loading the model in the fine-tuning code. But how to say, it is a bit troublesome and unnecessary, I also hope the finetuning code could be update...

**Comment by mavlyutovr** [comment]
@Incarceronn we will add that option to Translator. For now, once you have an initialized translator you can switch to the finetuned model using the following code snippet: 
```
translator.model.load_state_dict(torch.load("/path/to/checkpoint.pt"))
```

**Comment by FHT-hub** [comment]
> You can try to print and view the .pt file saved after fine-tuning. I found that the key of the state_dict and the key of the model parameters do not match. I successfully loaded the fine-tuned model by modifying the code for saving and loading the model in the fine-tuning code. But how to say, it is a bit troublesome and unnecessary, I also hope the finetuning code could be update...

Hello, I'm currently experiencing the same problem, can you ask in detail how you made the changes to the code? Thanks!
