### ISSUE TITLE
fairseq2 expects a float for sample rate

### ISSUE THREAD

**Issue by qmeeus** [facebookresearch/seamless_communication#94]
In `src/fairseq2/data/audio.py` `AudioDecoderOutput`, `WaveformToFbankInput` and `WaveformToFbankOutput`, the `sample_rate` is defined as float and not as an integer.

This leads to an error when executing this code sample:
```
import torch
import soundfile as sf
from seamless_communication.models.inference import Translator

waveform, sample_rate = sf.read("any_audio_file.wav")
waveform = torch.from_numpy(waveform)
translator = Translator("seamlessM4T_medium", vocoder_name_or_card="vocoder_36langs", device=torch.device("cuda:0"), dtype=torch.float32)
translated_text, *_ = translator.predict(waveform, "s2st", "fra")
# ValueError: The input sample rate must be of type `float`, but is of type `int` instead.
```

Although I think this is a mistake in fairseq2 code base, I report it here as well since fairseq2 is listed as a dependency. The fix, should they decide not to fix it, is to cast the sample_rate as a float in [this line](https://github.com/facebookresearch/seamless_communication/blob/c82b9800cff38775e882135471a1b251afa8ff2a/src/seamless_communication/models/inference/translator.py#L210)

[I have reported the issue in fairseq2 repo as well](https://github.com/facebookresearch/fairseq2/issues/9)

**Comment by YashasviMantha** [comment]
Interesting. Have you perhaps tried directly giving the path to the `wav` file to the `predict` method? Also, you can resample like this as well:

```
resample_rate = 16000
waveform, sample_rate = torchaudio.load('./source.wav')
resampler = torchaudio.transforms.Resample(sample_rate, resample_rate, dtype=waveform.dtype)
```

**Comment by qmeeus** [comment]
That is not really the point of the issue. Also, the model expects 44100 Hz as far as I know, so resampling the audio to 16 kHz is kind of pointless.

Thank you for the comment though

**Comment by cbalioglu** [comment]
(Copy pasting from fairseq2 issue)

@qmeeus thanks for the feedback! Please see [#12](https://github.com/facebookresearch/fairseq2/pull/12). `WaveformToFbankConverter` now accepts both float and integer sample rates. Note though that float sample rates are legitimate and there are use cases where they are used. In fact Kaldi (which torchaudio internally uses) accepts only floats as sample rate. Hope #12 resolves your issue though. I plan to release it as part of v0.1.1 tomorrow morning.
