### ISSUE TITLE
s2st

### ISSUE THREAD

**Issue by RayLam2022** [facebookresearch/seamless_communication#95]
I have encountered the following problem. When the mode is t2st, it works, but when the mode is s2st, the following error occurs. 

Runtime error:"Calculated padded input size per channel: (0). Kernel size: (1). Kernel size can't be greater than actual input size"

**Comment by RayLam2022** [comment]
Python3.8(ubuntu20.04)
torch2.0.1+cu118

**Comment by lin-xiaosheng** [comment]
Hello, I've also encountered the same issue. Could you please describe in detail how you resolved it?
