### ISSUE TITLE
ERROR: Cannot uninstall 'TBB'

### ISSUE THREAD

**Issue by luojiong** [facebookresearch/seamless_communication#96]
OS ubuntu 22.04
python version = Python 3.11.4

Im run  this command  python install .

He made the following error

` Installing collected packages: tbb, distlib, torcheval, soxr, rapidfuzz, portalocker, platformdirs, packaging, overrides, nodeenv, identify, filelock, click, cfgv, audioread, virtualenv, soundfile, sacrebleu, jiwer, torchaudio, pre-commit, librosa, fairseq2n, fairseq2, seamless-communication
  Attempting uninstall: tbb
    Found existing installation: TBB 0.2
ERROR: Cannot uninstall 'TBB'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall. `

![1693059806571](https://github.com/facebookresearch/seamless_communication/assets/28083937/8d678bab-db7f-4fcd-b67a-810a72100de2)

**Comment by danieljose** [comment]
I solved various installing problems with --no-deps, but probably this is not a good solution. But as is a wsl, I can just revert if needed in my case.

**Comment by luojiong** [comment]
I just tried this option and it really worked. Thank you
