### ISSUE TITLE
How to use local checkpoint for inference?

### ISSUE THREAD

**Issue by dsp6414** [facebookresearch/seamless_communication#99]
seamless_communication/assets/cards/seamlessM4T_medium.yaml Modified below:

name: seamlessM4T_medium
base: unity_nllb-200
model_arch: medium
checkpoint: "/home/app/models/multitask_unity_medium.pt"

get error:
fairseq2.assets.card.AssetCardError: The value of the field 'checkpoint' of the asset card 'seamlessM4T_medium' must be a valid URI, but is '/home/app/models/multitask_unity_medium.pt' instead.

**Comment by dsp6414** [comment]
"file://......" is OK

**Comment by dsp6414** [comment]
The performance is not very good.

**Comment by dsp6414** [comment]
😊

**Comment by cherry899** [comment]
excuse me, what about the utilization of the tokenier.model I downloaded?
